import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Quote } from "lucide-react";
import { additionalYouthCampStories, youthCampStories } from "@/data/youthCampStories";

const stories = [...youthCampStories, ...additionalYouthCampStories];

export default function YouthCampStoriesPage() {
    return <main className="bg-slate-50"><section className="relative isolate overflow-hidden bg-slate-950 py-24 text-white sm:py-32"><Image src="/events/youth-camp-3.jpg" alt="Youth Camp community" fill priority sizes="100vw" className="-z-20 object-cover opacity-40" /><div className="absolute inset-0 -z-10 bg-slate-950/70" /><div className="mx-auto max-w-4xl px-6 text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-300">DEO Church Benguet Youth Camp</p><h1 className="mt-5 text-5xl font-bold tracking-tight sm:text-6xl">Known and Chosen</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-200">Real stories of faith, friendship, and discovering that God knows each of us personally and has a purpose for our lives.</p><p className="mt-7 font-bold text-teal-300">Jeremiah 1:5</p></div></section><section className="py-20 sm:py-24"><div className="mx-auto max-w-5xl px-6"><Link href="/#stories" className="inline-flex items-center gap-2 text-sm font-bold text-teal-700 transition hover:text-teal-900"><ArrowLeft size={17} aria-hidden="true" /> Back to home</Link><div className="mt-10 grid gap-8">{stories.map((story, index) => <article key={story.name} className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 md:grid-cols-[0.75fr_1.25fr]"><div className="relative min-h-64"><Image src={story.image} alt={story.alt} fill sizes="(min-width: 768px) 34vw, 100vw" className="object-cover" /></div><div className="p-7 sm:p-10"><Quote className="text-teal-600" size={30} aria-hidden="true" /><p className="mt-5 text-sm font-bold uppercase tracking-[0.16em] text-teal-700">Story 0{index + 1}</p><h2 className="mt-2 text-3xl font-bold text-slate-900">{story.name}</h2><p className="mt-1 text-sm text-slate-500">Youth Camp participant{story.language ? ` - ${story.language}` : ""}</p><div className="mt-6 space-y-4 leading-relaxed text-slate-600">{story.story.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></article>)}</div></div></section></main>;
}
