"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ChevronLeft, ChevronRight, HeartHandshake, Mail, ShoppingBag, Users, WalletCards, X } from "lucide-react";
import { useState } from "react";

type Product = { id: string; name: string; description: string; price: number; category: string; images: string[]; stock: boolean };
const products: Product[] = [
    { id: "shirt-1", name: "DEO Church T-Shirt", description: "Comfortable premium cotton shirt with our church logo.", price: 350, category: "Apparel", images: ["/products/shirt-1.jpg"], stock: true },
    { id: "draw-string-bag-1", name: "DEO Church Drawstring Bag", description: "A convenient bag for daily needs.", price: 180, category: "Bags", images: ["/products/draw-string-bag-1.jpg"], stock: true },
    { id: "tote-1", name: "Canvas Tote Bag", description: "An eco-friendly tote bag for everyday use.", price: 180, category: "Bags", images: ["/products/tote-bag-1.jpg", "/products/tote-bag-2.jpg", "/products/tote-bag-3.jpg"], stock: true },
    { id: "mug-1", name: "Faith Mug", description: "Start the day with a reminder of faith.", price: 150, category: "Drinkware", images: ["/products/mug-1.jpg", "/products/mug-2.jpg"], stock: true },
    { id: "magnet-1", name: "Refrigerator Magnet", description: "A small daily reminder for your home or office.", price: 40, category: "Home & Office", images: ["/products/ref-magnet-1.jpg", "/products/ref-magnet-2.jpg", "/products/ref-magnet-3.jpg"], stock: true },
    { id: "bag-tag-1", name: "DEO Church Bag Tag", description: "A thoughtful tag for bags and belongings.", price: 70, category: "Accessories", images: ["/products/bag-tag-1.jpg"], stock: true },
    { id: "cap-1", name: "DEO Church Cap", description: "A comfortable branded cap for everyday wear.", price: 250, category: "Accessories", images: ["/products/cap-1.jpg"], stock: true },
];
const supporterStories = [
    ["Rose Rosales", "Supporting the youth ministry."], ["Kimberly Toyokan", "For God’s glory!"], ["Arsel Vergara", "Quality shirt, hindi tinipid."], 
    ["Exelyn Ani-Catalan", "More blessings to the church."], ["Mark Adrian", "Ang nice ng shirt, Thank you DEO."], ["Mika Martin", "Grabe, simple pero elepante."],
];
const impactAreas = [["Youth gatherings", "Creating safe spaces where young people can worship, learn, and belong."], ["Community outreach", "Serving people in Benguet with practical care and the love of Jesus."], ["Discipleship", "Providing resources and opportunities for people to grow in faith."], ["Church events", "Making room for prayer, worship, fellowship, and connection."]];

function ProductCard({ product, onView, selected, toggle }: { product: Product; onView: (product: Product) => void; selected: boolean; toggle: (product: Product) => void }) {
    return <article className="group overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-xl"><button type="button" onClick={() => onView(product)} className="relative block aspect-[4/3] w-full overflow-hidden text-left focus-visible:outline-2 focus-visible:outline-offset-[-3px] focus-visible:outline-teal-600"><Image src={product.images[0]} alt={product.name} fill sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-teal-800">{product.stock ? "Available" : "Out of stock"}</span></button><div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-teal-700">{product.category}</p><h3 className="mt-2 text-xl font-bold text-slate-900">{product.name}</h3><p className="mt-3 min-h-10 text-sm leading-relaxed text-slate-600">{product.description}</p><div className="mt-6 flex items-center justify-between gap-3"><span className="text-xl font-bold text-teal-700">₱{product.price.toLocaleString()}</span><div className="flex gap-2"><button type="button" onClick={() => onView(product)} className="rounded-xl border border-teal-600 px-3 py-2 text-sm font-bold text-teal-700 hover:bg-teal-50">View</button><button type="button" onClick={() => toggle(product)} className={`rounded-xl px-3 py-2 text-sm font-bold ${selected ? "bg-teal-100 text-teal-800" : "bg-teal-600 text-white hover:bg-teal-700"}`}>{selected ? "Added" : "Interested"}</button></div></div></div></article>;
}

export default function SupportPage() {
    const [category, setCategory] = useState<string | null>(null);
    const [selected, setSelected] = useState<Product[]>([]);
    const [viewing, setViewing] = useState<Product | null>(null);
    const [imageIndex, setImageIndex] = useState(0);
    const categories = Array.from(new Set(products.map((product) => product.category)));
    const visible = category ? products.filter((product) => product.category === category) : products;
    const toggle = (product: Product) => setSelected((current) => current.some((item) => item.id === product.id) ? current.filter((item) => item.id !== product.id) : [...current, product]);
    const openProduct = (product: Product) => { setViewing(product); setImageIndex(0); };
    const orderBody = encodeURIComponent(`Hello DEO Church! I am interested in: ${selected.map((product) => `${product.name} (₱${product.price})`).join(", ")}. Please confirm availability, payment details, and collection options.`);

    return <main>
        <section className="relative isolate overflow-hidden bg-slate-950 py-24 text-white sm:py-32"><Image src="/events/deo-church-benguet-5.jpg" alt="DEO Church Benguet community" fill priority sizes="100vw" className="-z-20 object-cover opacity-40" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950/95 via-slate-950/70 to-slate-950/35" /><div className="mx-auto max-w-6xl px-6"><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.18em] text-teal-300"><HeartHandshake size={17} aria-hidden="true" /> Support the mission</p><h1 className="mt-4 max-w-3xl text-5xl font-bold tracking-tight sm:text-6xl">Generosity makes room for ministry.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-200">Shop, give, pray, or serve—each act of support helps make a lasting difference in Benguet.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#shop" className="rounded-xl bg-teal-500 px-5 py-3 font-bold hover:bg-teal-400">Shop merchandise</a><Link href="/contact#message" className="rounded-xl border border-white/30 bg-white/10 px-5 py-3 font-bold hover:bg-white/20">Ask about giving</Link></div></div></section>

        <section className="bg-slate-50 py-16 sm:py-20"><div className="mx-auto grid max-w-6xl gap-5 px-6 md:grid-cols-3">{[[ShoppingBag, "Shop merchandise", "Choose a meaningful item that supports active ministries.", "Browse items", "#shop"], [WalletCards, "Give directly", "Contact the church for verified giving options and confirmation.", "Ask about giving", "/contact#message"], [HeartHandshake, "Pray and serve", "Stand with the church through prayer, skills, and time.", "Get involved", "/get-involved"]].map(([Icon, title, text, action, href]) => { const Symbol = Icon as typeof ShoppingBag; const content = <><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-teal-100 text-teal-700"><Symbol size={24} aria-hidden="true" /></span><h2 className="mt-5 text-2xl font-bold text-slate-900">{title as string}</h2><p className="mt-3 leading-relaxed text-slate-600">{text as string}</p><p className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-teal-700">{action as string} <ArrowRight size={16} aria-hidden="true" /></p></>; return (href as string).startsWith("#") ? <a key={title as string} href={href as string} className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 hover:-translate-y-1 hover:shadow-lg">{content}</a> : <Link key={title as string} href={href as string} className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 hover:-translate-y-1 hover:shadow-lg">{content}</Link>; })}</div></section>

        <section id="shop" className="scroll-mt-24 bg-white py-24 sm:py-28"><div className="mx-auto max-w-6xl px-6"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-700">Shop for the mission</p><h2 className="mt-4 text-4xl font-bold tracking-tight text-slate-900">Wear and share the vision.</h2><p className="mt-5 leading-relaxed text-slate-600">View an item for more photos, then add it to your inquiry. The church will confirm stock and payment before any order is placed.</p></div><div className="mt-8 flex flex-wrap gap-2">{[null, ...categories].map((item) => <button key={item ?? "all"} type="button" onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm font-bold ${category === item ? "bg-teal-600 text-white" : "bg-slate-100 text-slate-700 hover:bg-teal-50"}`}>{item ?? "All items"}</button>)}</div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map((product) => <ProductCard key={product.id} product={product} onView={openProduct} selected={selected.some((item) => item.id === product.id)} toggle={toggle} />)}</div>{selected.length > 0 && <div className="sticky bottom-5 z-20 mt-10 flex flex-col gap-4 rounded-2xl bg-slate-950 p-5 text-white shadow-2xl sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{selected.length} item{selected.length === 1 ? "" : "s"} selected</p><p className="mt-1 text-sm text-slate-300">Send an inquiry; availability and payment will be confirmed first.</p></div><a href={`mailto:deochurchbenguetchosenmission@gmail.com?subject=Merchandise%20order%20inquiry&body=${orderBody}`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-500 px-5 py-3 font-bold hover:bg-teal-400">Ask to order <Mail size={18} aria-hidden="true" /></a></div>}</div></section>

        <section className="bg-slate-50 py-24 sm:py-28"><div className="mx-auto max-w-6xl px-6"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-700">Giving with confidence</p><h2 className="mt-4 text-4xl font-bold tracking-tight text-slate-900">Direct giving, handled with care.</h2><p className="mt-5 leading-relaxed text-slate-600">Use only giving details confirmed by the official church contact channels. We will explain the verified payment option, intended ministry use, and confirmation process.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["1", "Contact the church", "Ask for verified giving options and the ministry area you want to support."], ["2", "Confirm payment details", "Use only details supplied through official DEO Church Benguet channels."], ["3", "Receive confirmation", "Keep your confirmation and contact us with any questions about your gift."]].map(([number, title, text]) => <article key={number} className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><span className="text-sm font-bold text-teal-700">STEP {number}</span><h3 className="mt-4 text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-relaxed text-slate-600">{text}</p></article>)}</div><Link href="/contact#message" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-teal-600 px-5 py-3 font-bold text-white hover:bg-teal-700">Ask about giving <ArrowRight size={18} aria-hidden="true" /></Link></div></section>

        <section className="bg-white py-24 sm:py-28"><div className="mx-auto max-w-6xl px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-700">Your support in action</p><h2 className="mt-4 text-4xl font-bold tracking-tight text-slate-900">Where generosity makes a difference.</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{impactAreas.map(([title, text], index) => <article key={title} className="rounded-2xl bg-teal-50 p-6"><span className="text-sm font-bold text-teal-700">0{index + 1}</span><h3 className="mt-4 text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-relaxed text-slate-600">{text}</p></article>)}</div><div className="mt-12 grid gap-4 rounded-3xl bg-slate-950 p-7 text-white sm:grid-cols-4 sm:p-9">{[["Your support", "Purchase, gift, prayer, or time"], ["Ministry resources", "Tools and preparation"], ["Gatherings and outreach", "Church and community connection"], ["People reached", "Lives touched by Jesus’ love"]].map(([title, text], index) => <div key={title} className="relative"><p className="text-sm font-bold text-teal-300">0{index + 1}</p><h3 className="mt-2 font-bold">{title}</h3><p className="mt-2 text-sm text-slate-300">{text}</p>{index < 3 && <ArrowRight className="absolute -right-3 top-7 hidden text-teal-300 sm:block" size={18} aria-hidden="true" />}</div>)}</div></div></section>

        <section className="bg-teal-700 py-24 text-white sm:py-28"><div className="mx-auto max-w-6xl px-6"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-100">Supporter stories</p><h2 className="mt-4 text-4xl font-bold tracking-tight">A community that gives together.</h2></div><p className="max-w-sm text-teal-50">Stories are shared only with permission and can be updated or removed on request.</p></div><div className="mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-4">{supporterStories.map(([name, story]) => <article key={name} className="w-72 shrink-0 snap-start rounded-2xl bg-white/10 p-6 backdrop-blur-sm"><Users className="text-teal-200" size={25} aria-hidden="true" /><blockquote className="mt-5 text-lg font-medium leading-relaxed">“{story}”</blockquote><p className="mt-6 text-sm font-bold text-teal-200">{name}</p></article>)}</div></div></section>

        {viewing && <div role="dialog" aria-modal="true" aria-label={`${viewing.name} details`} className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/80 p-4" onClick={() => setViewing(null)}><div className="relative grid max-h-[90vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white sm:grid-cols-2" onClick={(event) => event.stopPropagation()}><div className="relative min-h-80 bg-slate-100"><Image src={viewing.images[imageIndex]} alt={`${viewing.name}, image ${imageIndex + 1}`} fill sizes="(min-width: 640px) 50vw, 100vw" className="object-cover" />{viewing.images.length > 1 && <><button type="button" onClick={() => setImageIndex((current) => (current - 1 + viewing.images.length) % viewing.images.length)} className="absolute left-3 top-1/2 -translate-y-1/2 rounded-full bg-slate-950/60 p-2 text-white" aria-label="Previous product image"><ChevronLeft size={20} /></button><button type="button" onClick={() => setImageIndex((current) => (current + 1) % viewing.images.length)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full bg-slate-950/60 p-2 text-white" aria-label="Next product image"><ChevronRight size={20} /></button></>}</div><div className="p-7 sm:p-9"><button type="button" onClick={() => setViewing(null)} className="absolute right-4 top-4 rounded-full bg-white/90 p-2 text-slate-800 shadow" aria-label="Close product details"><X size={20} /></button><p className="text-sm font-bold uppercase tracking-[0.14em] text-teal-700">{viewing.category}</p><h2 className="mt-3 text-3xl font-bold text-slate-900">{viewing.name}</h2><p className="mt-4 leading-relaxed text-slate-600">{viewing.description}</p><p className="mt-6 text-2xl font-bold text-teal-700">₱{viewing.price.toLocaleString()}</p><p className="mt-3 text-sm font-semibold text-teal-700">{viewing.stock ? "Available — confirm current stock with the church." : "Please ask the church about availability."}</p><button type="button" onClick={() => { toggle(viewing); setViewing(null); }} className="mt-7 rounded-xl bg-teal-600 px-5 py-3 font-bold text-white hover:bg-teal-700">{selected.some((item) => item.id === viewing.id) ? "Remove from inquiry" : "Add to inquiry"}</button></div></div></div>}
    </main>;
}
